# Site settings
title: Fang-Li Blog
SEOTitle: 虫大侠的博客 | Fang-Li Blog
header-img: img/home-bg.jpg
email: Fang-Li@gmail.com
description: "关于前端与设计、黑客与画家 | 虫大侠，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Fang-Li虫大侠 的个人博客，与你一起发现更大的世界。"
keyword: "虫大侠, Fang-Li虫大侠, Fang-Li, 鬼栈, Fang-Li, @Fang-Li, 虫大侠的博客, Fang-Li Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://huangxuan.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     Fang-Li
zhihu_username:     Fang-Li
github_username:    Fang-Li
twitter_username:   Fang-Li
#facebook_username:  Fang-Li
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: Fang-Li

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
sidebar-avatar: /img/avatar-Fang-Li.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "乱序",
        href: "http://mida.re/"
    },{
        title: "前端外刊评论",
        href: "http://qianduan.guru/"
    },{
        title: "天镶的博客",
        href: "http://lingyu.wang/"
    },{
        title: "Luke 的自留地",
        href: "http://hmqk1995.github.io"
    },{
        title: "Ebn's Blog",
        href: "http://ebnbin.com/"
    },{
        title: "SmdCn's Blog",
        href: "http://blog.smdcn.net"
    },{
        title: "解旻的博客",
        href: "http://xieminis.me/"
    },{
        title: "DHong Say",
        href: "http://dhong.co"
    },{
        title: "尹峰以为",
        href: "http://ingf.github.io/"
    },{
        title: "前端神盾局",
        href: "http://wepiaofei.github.io/blog/"
    }
]

theme: jekyll-theme-leap-day